VAGRANTFILE_API_VERSION = '2'
NETWORK_FILE_SYSTEM = false
box = 'ubuntu/trusty64'
box_url = 'http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = box
	config.vm.box_url = box_url
	config.vm.network :private_network, ip: '10.0.10.10'
	
	config.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", "1024"]
			vb.gui = true
	end
	
	config.vm.provision :shell, path: "bootstrap.sh"
	
end

